#!/bin/bash

# Lists of possible argument values
FOLDERS=("sac-vp" "sac-fr+vp" "sac-vp+cp" "sac-ws+pc" "sac-fr+ws+pc" "sac-ws+pc+cp" "ppo-vp" "ppo-fr+vp" "ppo-vp+cp" "ppo-ws+pc" "ppo-fr+ws+pc" "ppo-ws+pc+cp")
PORTS=(4) # 5 6
GENS=("True" "False")

# Loop over each combination of arguments
for folder in "${FOLDERS[@]}"
do
    for ports in "${PORTS[@]}"
    do
        for gen in "${GENS[@]}"
        do
            echo "Running experiment with folder=$folder, ports=$ports, gen=$gen"

            # Run the Python script with the current arguments
            python your_script.py --folder "$folder" --ports $ports --gen $gen
        done
    done
done
