import time
from typing import Optional, Iterable, List, Tuple, Dict

import torch
import torch as th
from torch import Tensor
from tensordict.tensordict import TensorDict
from torchrl.envs.common import EnvBase
from torchrl.data import (
    BoundedTensorSpec,
    CompositeSpec,
    UnboundedContinuousTensorSpec,
    UnboundedDiscreteTensorSpec,
)
from rl4co.envs.common.base import RL4COEnvBase
from rl4co.envs.common.utils import Generator

# Modules
from environment.generator import MPP_Generator
from environment.utils import *

# Logger
from rl4co.utils.pylogger import get_pylogger
log = get_pylogger(__name__)

class MasterPlanningEnv(RL4COEnvBase):
    """Master Planning Problem (MPP) environment for Container Vessels Stowage Planning.

    Any episode in the MPP environment consists of |K|*|T| steps, where k \in K is set of cargo classes and \tau \in T
    is set of possible transports. The generator provides stochastic demand, where the agent only observes realized
    demand at the current ports. The future ports in the voyage are unknown, hence, the agent only observes the mean
    and std dev of the demand distribution. Hence, we define the initial embedding of the environment based on:
    - Cargo parameters:
        - POL: Ports of loading P = {0,1,...,|P|-1}
        - POD: Port of discharge P = {1,...,|P|}
        - cargo_class: Cargo classes K = {long_term, spot} \times {2 teus} \times {3 weights}
        - weight: Container weight in tonnes {1,2,3}
        - teu: Container Twenty-Foot-Equivalent units {1, 2}
        - revenue: Revenue generated by the container based on {long_term, spot} and distance between POL and POD
        # - discharge: Discharge flag (only first step of each port will discharge containers)
    - Demand distribution:
        - expected_demand: Expected demand of demand distribution
        - std_demand: Standard deviation of demand distribution

    At each step, the agent acts by loading containers characterized by (k,\tau) onto the vessel. The transitions are
    deterministic, i.e., containers are loaded and discharged based on the demand and vessel constraints. The reward
    The reward is computed based on the revenue generated by the loaded containers, as well as penalties for hatch
    overstowage. Furthermore, we have a set of constraints that the agent must satisfy, such as TEU capacity, cargo
    demand limit, stability limits (LCG,VCG), and the crane makespan limit.

    The environment has the following state variables: # todo: update this text!
    - Demand variables:
        - current_demand: Realized demand at time t
        - observed_demand: Observed demand at the current port

    - Vessel variables:
        - location utilization: Utilization of vessel locations at time t
        - clip_max: Residual TEU capacity of the vessel at time t
        - lhs_A: Left-hand side of the constraint matrix at time t
        - rhs: Right-hand side of the constraint matrix at time t
        - violation: Constraint violation of action at time t-1 (result of previous action)

    - Aggregated variables:
        - total_revenue: Total revenue during episode until time t
        - total_overstowage: Total hatch overstowage costs during episode until time t

    Compact formulation of constraints:
        Suppose we have a regular MIP in the form Ax <= b, where:
        - A:        constraint matrix of shape [n_constraints, B*D*K*T].
        - x:        Decision variable of MIP with shape [batch, B*D*K*T].
        - b:        Bound vector of shape [batch, n_constraints].

        Our policy is not the same shape as the MIP decision. We need to adjust the compact form to fit the policy.
        First, we rewrite x = x_t + x^{AC}.
        Second, we rewrite the constraints as A_t x_t <= b_t - Ax^{AC}, where:
        - x^{AC}:   Vessel's aggregated arrival condition of shape [batch, B*D**K*T].
        - x_t:      Policy output of shape [batch, B*D,].
        - A_t:      constraint matrix of shape [n_constraints, B*D].
        - b_t:      Bound vector of shape [batch, n_constraints].

        The compact form is used to compute the violation of the constraints for each action.
    """

    name = "mpp"

    def __init__(self, **kwargs):
        super().__init__()
        # Sets
        self.P = kwargs.get("ports") # Number of ports
        self.B = kwargs.get("bays")  # Number of bays
        self.D = kwargs.get("decks") # Number of decks
        self.T = int((self.P ** 2 - self.P) / 2) # Number of (POL,POD) transports
        self.CC = kwargs.get("customer_classes")  # Number of customer contracts
        self.K = kwargs.get("cargo_classes") * self.CC # Number of container classes
        self.W = kwargs.get("weight_classes")  # Number of weight classes

        # Init fns
        self.float_type = kwargs.get("float_type", th.float16)
        self.demand_uncertainty = kwargs.get("demand_uncertainty", False)
        self.generator = MPP_Generator(**kwargs)
        self._make_spec(self.generator)
        self._compact_form_shapes()
        self.zero = th.tensor([0], device=self.generator.device, dtype=self.float_type)
        self.padding = th.tensor([self.P-1], device=self.generator.device, dtype=th.int32)

        # Parameters:
        # Transport and cargo characteristics
        self.ports = torch.arange(self.P, device=self.generator.device)
        self.transport_idx = get_transport_idx(self.P, device=self.generator.device)

        # Capacity in TEU per location (bay,deck)
        c = kwargs.get("capacity")
        self.capacity = th.full((self.B, self.D,), c[0], device=self.generator.device, dtype=self.float_type)
        self.norm_capacity = self.capacity
        self.total_capacity = th.sum(self.capacity)
        self.teus = th.arange(1, self.K // (self.CC * self.W) + 1, device=self.generator.device, dtype=self.float_type) \
            .repeat_interleave(self.W).repeat(self.CC)
        self.teus_episode = th.cat([self.teus.repeat(self.T)])
        self.weights = th.arange(1, self.W + 1, device=self.generator.device, dtype=self.float_type).repeat(self.K // self.W)
        self.duration = self.transport_idx[:, 1] - self.transport_idx[:, 0]

        # Revenue and costs
        self.revenues_matrix = self._precompute_revenues()
        self.ho_costs = kwargs.get("hatch_overstowage_costs") #* th.mean(self.revenues)
        self.lc_costs = kwargs.get("long_crane_costs") #* th.mean(self.revenues)
        self.ho_mask = kwargs.get("hatch_overstowage_mask")
        self.CI_target = kwargs.get("CI_target")

        # Transport sets
        self._precompute_transport_sets()
        # Step ordering: descending distance, longterm > spot; ascending TEU, ascending weight
        self.ordering = kwargs.get("episode_order")
        if self.ordering == "max_distance_then_priority":
            self.ordered_steps = self._precompute_order_max_distance_then_priority()
        elif self.ordering == "greedy_revenue":
            self.ordered_steps = self._precompute_order_greedy_revenue()
        elif self.ordering == "priority_then_greedy":
            raise NotImplementedError("Priority then greedy ordering is not implemented yet.")
        else:
            self.ordered_steps = self._precompute_order_standard()
        self.ordered_steps = th.cat([self.ordered_steps, self.padding])
        self.k, self.tau = get_k_tau_pair(self.ordered_steps, self.K)
        self.pol, self.pod = get_pol_pod_pair(self.tau, self.P)
        # self.pol, self.pod, self.k, self.tau = self._add_padding(self.pol, self.pod, self.k, self.tau)
        self.revenues = self.revenues_matrix[self.k, self.tau]
        self._precompute_transport_sets_episode()
        self.next_port_mask = self._precompute_next_port_mask()
        self.transform_tau_to_pol = get_pols_from_transport(self.transport_idx, self.P, dtype=self.float_type)
        self.transform_tau_to_pod = get_pods_from_transport(self.transport_idx, self.P, dtype=self.float_type)

        # Stability
        self.stab_delta = kwargs.get("stability_difference")
        self.LCG_target = kwargs.get("LCG_target")
        self.VCG_target = kwargs.get("VCG_target")
        self.longitudinal_position = th.arange(1/self.B, self.B * 2/self.B, 2/self.B,
                                               device=self.generator.device, dtype=self.float_type)
        self.vertical_position = th.arange(1/self.D, self.D * 2/self.D, 2/self.D,
                                           device=self.generator.device, dtype=self.float_type)
        self.lp_weight = th.einsum("d, b -> bd", self.weights, self.longitudinal_position).unsqueeze(0)
        self.vp_weight = th.einsum("d, c -> cd", self.weights, self.vertical_position).unsqueeze(0)
        self.stability_params_lhs = self._precompute_stability_parameters()

        # Constraints
        self.constraint_signs = th.tensor([1, 1, -1, 1, -1], device=self.generator.device, dtype=self.float_type)
        self.swap_signs_stability = th.tensor([1, -1, -1, -1, -1], device=self.generator.device, dtype=self.float_type)
        self.A = self._create_constraint_matrix(shape=(self.n_constraints, self.n_action, self.T, self.K))

    def _make_spec(self, generator:Optional[Generator] = None) -> None:
        """Define the specs for observations, actions, rewards, and done flags."""
        self.observation_spec = CompositeSpec(
            observation=UnboundedContinuousTensorSpec(shape=(214)),  # Define shape as needed
        )
        self.action_spec = BoundedTensorSpec(
            shape=(self.B*self.D),  # Define shape as needed
            low=0.0,
            high=10,  # Define high value as needed
        )
        self.reward_spec = UnboundedContinuousTensorSpec(shape=(1,))
        self.done_spec = UnboundedDiscreteTensorSpec(shape=(1,), dtype=th.bool)

    def check_solution_validity(self, td, actions) -> th.bool:
        """Check solution validity"""
        # todo: add validity logic
        return True

    def _check_done(self, t: Tensor) -> Tensor:
        """Determine if the episode is done based on the state."""
        return (t == (self.T*self.K) - 1).view(-1,1)

    def _step(self, td: TensorDict) -> TensorDict:
        """Perform a step in the environment and return the next state."""
        ## Extraction and precompute
        action, realized_demand, lhs_A, rhs, t, batch_size = self._extract_from_td(td)
        pol, pod, tau, k, rev = self._extract_cargo_parameters_for_step(t[0])
        utilization, target_long_crane, total_metrics = self._extract_from_state(td["state"])
        demand_obs = self._extract_from_obs(td["obs"], batch_size)

        ## Current state
        # Check done, update utilization, and compute violation
        done = self._check_done(t)
        utilization = self._update_state_loading(action, utilization, tau, k,)
        violation = compute_violation(action.view(*batch_size, 1, -1), lhs_A, rhs)
        # Compute long crane moves
        long_crane_moves = self._compute_long_crane(utilization, pol)
        # Compute od-pairs
        pol_locations, pod_locations = self._compute_pol_pod_locations(utilization)
        agg_pol_location, agg_pod_location = self._aggregate_pol_pod_location(pol_locations, pod_locations)
        # Compute total loaded
        sum_action = action.sum(dim=(-2, -1)).unsqueeze(-1)
        total_metrics["total_loaded"] += sum_action
        # total_metrics["total_loaded"] += th.min(sum_action, demand_obs["current_demand"])
        # print("act", sum_action.T)
        # print("dem", demand_obs["current_demand"].T)
        # print("min", th.min(sum_action, demand_obs["current_demand"]).T)
        # print("relu(sum - dem).mean()", th.relu(sum_action - demand_obs["current_demand"]).mean())

        ## Reward
        revenue = sum_action * self.revenues[t[0]]
        # revenue = th.min(sum_action, demand_obs["current_demand"]) * self.revenues[t[0]]
        profit = revenue.clone()
        if self.next_port_mask[t].any():
            # Compute aggregated: overstowage and long crane excess
            overstowage = self._compute_hatch_overstowage(utilization, pol)
            excess_crane_moves = th.clamp(long_crane_moves - target_long_crane.view(-1, 1), min=0)
            # Compute costs
            ho_costs = overstowage.sum(dim=-1, keepdim=True) * self.ho_costs
            lc_costs = excess_crane_moves.sum(dim=-1, keepdim=True) * self.lc_costs
            cost = ho_costs + lc_costs
            profit -= cost
        else:
            cost = th.zeros_like(profit)

        ## Transition to next step
        # Update next state
        t = t + 1
        next_state_dict = self._update_next_state(utilization, target_long_crane, long_crane_moves,
                                                  realized_demand, demand_obs, t,)
        if not done.any():
            # Update feasibility: lhs_A, rhs, clip_max based on next state
            lhs_A = self.create_lhs_A(lhs_A, t)
            rhs = self.create_rhs(next_state_dict["utilization"], next_state_dict["current_demand"], batch_size)
            # Express residual capacity in number of containers for next step
            residual_capacity = th.clamp(self.norm_capacity - next_state_dict["utilization"].sum(dim=-2)
                                         @ self.teus, min=self.zero) / self.teus_episode[t].view(-1, 1, 1)
        else:
            residual_capacity = th.zeros_like(td["clip_max"], dtype=self.float_type)

        # # Update action mask
        # # action_mask[t] = 0
        # mask_condition = (t[0] % self.K == 0)
        # min_pod = self._compute_min_pod(pol_locations, pod_locations )
        # new_mask = self._prevent_HO_mask(action_mask, pod, pod_locations, min_pod)
        # action_mask = th.where(mask_condition, new_mask, action_mask)

        # Only for final port
        if t[0] == self.T*self.K:
            # Compute last port long crane excess
            lc_moves_last_port = self._compute_long_crane(utilization, pol)
            lc_excess_last_port = th.clamp(lc_moves_last_port - next_state_dict["target_long_crane"].view(-1,1), min=0)

            # Compute metrics
            excess_crane_moves += lc_excess_last_port
            lc_cost_ = lc_excess_last_port.sum(dim=-1, keepdim=True) * self.lc_costs
            profit -= lc_cost_
            cost += lc_cost_
            lc_costs += lc_cost_

        # Track metrics
        total_metrics["total_rc"] += residual_capacity.view(*batch_size, -1)
        total_metrics["total_revenue"] += revenue
        total_metrics["total_cost"] += cost
        # Normalize revenue \in [0,1]:
        # revenue_norm = rev_t / max(rev_t) * min(q_t, sum(a_t)) / q_t
        normalize_revenue = self.revenues.max() * demand_obs["current_demand"]
        # Normalize accumulated cost \in [0, t_cost], where t_cost is the time at which we evaluate cost:
        # cost_norm = cost_{t_cost} / E[q_t]
        normalize_cost = realized_demand.view(*batch_size, -1)[:,:t[0]].sum(dim=-1, keepdims=True) / t[0]
        # Normalize reward: r_t = revenue_norm - cost_norm
        # We have spikes over delayed costs at specific time steps.
        reward = (revenue.clone() / normalize_revenue) - (cost.clone() / normalize_cost)

        # Update td output
        td.update({
            "state":{
                # Vessel
                "utilization": next_state_dict["utilization"],
                "target_long_crane": next_state_dict["target_long_crane"],

                # Performance
                "total_loaded": total_metrics["total_loaded"],
                "total_revenue": total_metrics["total_revenue"],
                "total_cost": total_metrics["total_cost"],
                "total_rc": total_metrics["total_rc"],
            },
            "obs":{
                # Demand
                "current_demand": next_state_dict["current_demand"].view(*batch_size, 1),
                "observed_demand": next_state_dict["observed_demand"].view(*batch_size, self.T*self.K),
                "expected_demand": next_state_dict["expected_demand"].view(*batch_size, self.T*self.K),
                "std_demand": next_state_dict["std_demand"].view(*batch_size, self.T*self.K),
                # Vessel
                "residual_capacity": residual_capacity.view(*batch_size, self.B * self.D),
                "residual_lc_capacity": next_state_dict["residual_lc_capacity"].view(*batch_size, self.B-1),
                "pol_location": pol_locations.view(*batch_size, -1).to(self.float_type),
                "pod_location": pod_locations.view(*batch_size, -1).to(self.float_type),
                "agg_pol_location": agg_pol_location.view(*batch_size, self.B * self.D),
                "agg_pod_location": agg_pod_location.view(*batch_size, self.B * self.D),
            },

            # Feasibility and constraints
            "lhs_A": lhs_A,
            "rhs": rhs,
            "violation": violation,
            "clip_max": residual_capacity.view(*batch_size, self.B*self.D),
            # Action, reward, done and step
            "action": action.view(*batch_size, self.B*self.D),
            "reward": reward,
            "profit": profit,
            "revenue": revenue,
            "cost": cost,
            "done": done,
            "timestep":t,
        })
        return td

    def _reset(self,  td: Optional[TensorDict] = None,  batch_size=None) -> TensorDict:
        """Reset the environment to the initial state."""
        # Reordering on demand
        td["realized_demand"] = td["realized_demand"].view(*batch_size, self.T, self.K)
        td["observed_demand"] = td["observed_demand"].view(*batch_size, self.T, self.K)
        td["expected_demand"] = td["expected_demand"].view(*batch_size, self.T, self.K)
        td["std_demand"] = td["std_demand"].view(*batch_size, self.T, self.K)

        # Initialize
        # Parameters
        device = td.device
        t = th.zeros(*batch_size, dtype=th.int64)
        pol, pod, tau, k, rev = self._extract_cargo_parameters_for_step(t[0])
        # Action mask and clipping
        residual_capacity = (self.norm_capacity / self.teus[t[0]]).unsqueeze(0).repeat(*batch_size, 1, 1)
        action_mask = th.ones((*batch_size, self.B*self.D), dtype=th.bool, device=device)
        # Vessel state
        target_long_crane = self._compute_target_long_crane(td["realized_demand"].view(*batch_size, self.T, self.K),
                                                            self.moves_idx[t[0]])
        utilization = th.zeros((*batch_size, self.B, self.D, self.T, self.K), device=device, dtype=self.float_type)
        locations_utilization = th.zeros_like(action_mask, dtype=self.float_type)
        port_locations = th.zeros((*batch_size, self.B*self.D*self.P), dtype=self.float_type)
        # Demand
        current_demand = td["observed_demand"][:, tau, k].view(*batch_size, 1).clone() # clone to prevent in-place!
        td["observed_demand"][:, tau, k] = 0
        td["expected_demand"][:, tau, k] = 0
        td["std_demand"][:, tau, k] = 0
        # Constraints
        lhs_A = self.create_lhs_A(
            th.zeros((*batch_size, self.n_constraints, self.B * self.D),  device=device, dtype=self.float_type), t)
        rhs = self.create_rhs(utilization, current_demand, batch_size)

        # Init tds - state: internal state
        initial_state = TensorDict({
            # Vessel
            "utilization": utilization,
            "target_long_crane": target_long_crane,
            # Performance
            "total_loaded": th.zeros_like(current_demand, dtype=self.float_type),
            "total_revenue": th.zeros_like(current_demand, dtype=self.float_type),
            "total_cost": th.zeros_like(current_demand, dtype=self.float_type),
            "total_rc": th.zeros_like(locations_utilization),
        }, batch_size=batch_size, device=device,)

        # Init tds - obs: observed by embeddings
        initial_obs = TensorDict({
            # Demand
            "current_demand": current_demand.view(*batch_size, 1),
            "observed_demand": td["observed_demand"].view(*batch_size, self.T*self.K),
            "expected_demand": td["expected_demand"].view(*batch_size, self.T*self.K),
            "std_demand": td["std_demand"].view(*batch_size, self.T*self.K),
            # Vessel
            "residual_capacity": residual_capacity.view(*batch_size, self.B*self.D),
            "residual_lc_capacity": target_long_crane.unsqueeze(-1).expand(-1, self.B-1),
            "pol_location": th.zeros_like(port_locations, dtype=self.float_type),
            "pod_location": th.zeros_like(port_locations, dtype=self.float_type),
            "agg_pol_location": th.zeros_like(locations_utilization),
            "agg_pod_location": th.zeros_like(locations_utilization),
        }, batch_size=batch_size, device=device,)

        # Init tds - full td
        td = TensorDict({
            # State + obs
            "state": initial_state,
            "obs": initial_obs,
            # Action mask and clipping
            "action": th.zeros_like(action_mask, dtype=self.float_type),
            "action_mask": action_mask.view(*batch_size, -1),
            "clip_min": th.zeros_like(residual_capacity, dtype=self.float_type).view(*batch_size, self.B*self.D, ),
            "clip_max": residual_capacity.view(*batch_size, self.B*self.D),
            # Constraints
            "lhs_A": lhs_A,
            "rhs":  rhs,
            "violation": th.zeros_like(rhs, dtype=self.float_type),
            # Reward, done and step
            "reward": th.zeros_like(t, dtype=self.float_type),
            "profit": th.zeros_like(t, dtype=self.float_type),
            "revenue": th.zeros_like(t, dtype=self.float_type),
            "cost": th.zeros_like(t, dtype=self.float_type),
            "done": th.zeros_like(t, dtype=th.bool),
            "timestep": t,
        }, batch_size=batch_size, device=device)
        return td

    # Extraction functions
    def _extract_from_td(self, td) -> Tuple:
        """Extract action, reward and step from the TensorDict."""
        # Must clone to avoid in-place operations!
        batch_size = td.batch_size
        timestep = td["timestep"].clone()
        action = td["action"].view(*batch_size, self.B, self.D,).clone()
        # action_mask = td["action_mask"].clone()
        realized_demand = td["realized_demand"].view(*batch_size, self.T, self.K).clone()
        lhs_A = td["lhs_A"].clone()
        rhs = td["rhs"].clone()
        return action, realized_demand, lhs_A, rhs, timestep, batch_size

    def _extract_cargo_parameters_for_step(self, t) -> Tuple:
        """Extract cargo-related parameters"""
        pol = self.pol[t]
        pod = self.pod[t]
        k = self.k[t]
        tau = self.tau[t]
        rev_t = self.revenues[t]
        return pol, pod, tau, k, rev_t

    def _extract_from_state(self, state) -> Tuple:
        """Extract and clone state variables from the state TensorDict."""
        # Vessel-related variables
        utilization = state["utilization"].clone()
        target_long_crane = state["target_long_crane"].clone()
        # Additional variables
        total_metrics = {
            "total_loaded": state["total_loaded"].clone(),
            "total_revenue": state["total_revenue"].clone(),
            "total_cost": state["total_cost"].clone(),
            "total_rc": state["total_rc"].clone(),
        }
        return utilization, target_long_crane, total_metrics

    def _extract_from_obs(self, obs, batch_size) -> Dict:
        """Extract and clone state variables from the obs TensorDict."""
        output = {
            # clones are needed to prevent in-place
            "current_demand": obs["current_demand"].clone(),
            "observed_demand": obs["observed_demand"].view(*batch_size, self.T, self.K).clone(),
            "expected_demand": obs["expected_demand"].view(*batch_size, self.T, self.K).clone(),
            "std_demand": obs["std_demand"].view(*batch_size, self.T, self.K).clone(),
        }
        return output

    # Reward/costs functions
    def _get_reward(self, td, utilizations) -> Tensor:
        """Compute total profit for episode"""
        return td["state"]["total_revenue"] - td["state"]["total_cost"]

    def _compute_min_pod(self,pod_locations: Tensor) -> Tensor:
        """Compute min_pod based on utilization"""
        min_pod = th.argmax(pod_locations.to(self.float_type), dim=-1)
        min_pod[min_pod == 0] = self.P
        return min_pod

    def _compute_pol_pod_locations(self, utilization: Tensor) -> Tuple[Tensor, Tensor]:
        """Compute POL and POD locations based on utilization"""
        util = utilization.permute(0, 1, 2, 4, 3)
        pol_locations = (util @ self.transform_tau_to_pol).sum(dim=-2) != 0
        pod_locations = (util @ self.transform_tau_to_pod).sum(dim=-2) != 0
        return pol_locations, pod_locations

    def _aggregate_pol_pod_location(self, pol_locations: Tensor, pod_locations: Tensor,) -> Tuple:
        """Aggregate pol_locations and pod_locations into:
            - pod: [max(pod_d0), min(pod_d1)]
            - pol: [min(pol_d0), max(pol_d1)]"""
        ## Get load indicators - we load below deck that is blocked
        # For above deck (d=0):
        min_pol_d0 = torch.where(pol_locations[:, :, 0, :] > 0, self.ports + 1, self.P).min(dim=-1).values
        min_pol_d0 = torch.where(min_pol_d0 == self.P, 0, min_pol_d0)
        # For below deck (d=1):
        max_pol_d1 = torch.where(pol_locations[:, :, 1, :] > 0, self.ports + 1, 0).max(dim=-1).values
        agg_pol_locations = torch.stack((min_pol_d0, max_pol_d1), dim=-1)

        ## Get discharge indicators - we discharge below deck that is blocked
        # For above deck (d=0):
        max_pod_d0 = torch.where(pod_locations[:, :, 0, :] > 0, self.ports+1, 0).max(dim=-1).values
        # For below deck (d=1):
        min_pod_d1 = torch.where(pod_locations[:, :, 1, :] > 0, self.ports+1, self.P).min(dim=-1).values
        min_pod_d1 = torch.where(min_pod_d1 == self.P, 0, min_pod_d1)
        agg_pod_locations = torch.stack((max_pod_d0, min_pod_d1), dim=-1)
        # Return indicators
        return agg_pol_locations.to(self.float_type), agg_pod_locations.to(self.float_type)

    def _compute_overstowage_loading_indicator(self, pod_locations: Tensor,) -> Tensor:
        """Indicate if overstowage is present due to discharge by: max(pod_d0) > min(pod_d1)
        Output: Positive integer tensor with shape [batch, bay, deck]"""
        # Get the number of pods
        pods = torch.arange(self.P, device=self.generator.device)
        # For above deck (d=0), compute the min POD index where value is 1 (non-zero elements)
        max_pod_d0 = torch.where(pod_locations[:, :, 0, :] > 0, pods, float('-inf')).max(dim=-1).values
        # For below deck (d=1), compute the max POD index where value is 1 (non-zero elements)
        min_pod_d1 = torch.where(pod_locations[:, :, 1, :] > 0, pods, float('inf')).min(dim=-1).values
        # Stack the results into the desired shape [batch, bay, 2]
        output = torch.stack((max_pod_d0, min_pod_d1), dim=-1)
        return output

    def _compute_hatch_overstowage(self, utilization: Tensor, single_pol: Tensor) -> Tensor:
        """Get hatch overstowage based on ac_transport and moves"""
        # Get indices
        ac_transport = self.remain_on_board_transport[single_pol]
        moves = self.moves_idx[single_pol]
        # Compute hatch overstowage
        hatch_open = utilization[:, :, 1:, moves, :].sum(dim=(2, 3, 4)) > 0
        hatch_overstowage = utilization[:, :, :1, ac_transport, :].sum(dim=(2, 3, 4)) * hatch_open
        return hatch_overstowage

    def _compute_target_long_crane(self, realized_demand: Tensor, moves: Tensor) -> Tensor:
        """Compute target crane moves per port:
        - Get total crane moves per port: load_moves + discharge_moves
        - Get optimal crane moves per adjacent bay by: 2 * total crane moves / B
        - Get adjacent capacity by: sum of capacity of adjacent bays
        - Get max capacity of adjacent bays by: max of adjacent capacity

        Return element-wise minimum of optimal crane moves and max capacity"""
        # Calculate optimal crane moves based per adjacent bay based on loading and discharging
        total_crane_moves = realized_demand[:, moves, :].sum(dim=(1,2))
        # Compute adjacent capacity and max capacity
        max_capacity = ((self.norm_capacity[:-1] + self.norm_capacity[1:]).sum(dim=-1)).max()
        # Compute element-wise minimum of crane moves and target long crane
        optimal_crane_moves_per_adj_bay = 2 * total_crane_moves / self.B
        return self.CI_target * th.minimum(optimal_crane_moves_per_adj_bay, max_capacity)

    def _compute_long_crane(self, utilization: Tensor, single_pol: Tensor) -> Tensor:
        """Compute long crane moves based on utilization"""
        moves_idx = self.moves_idx[single_pol].to(utilization.dtype).view(1, 1, 1, self.T, 1)
        moves_per_bay = (utilization * moves_idx).sum(dim=(2, 3, 4))
        return moves_per_bay[:, :-1] + moves_per_bay[:, 1:]

    def _prevent_HO_mask(self, mask:Tensor, pod: Tensor,pod_locations:Tensor, min_pod:Tensor) -> Tensor:
        """
        Mask action to prevent hatch overstowage. Deck indices: 0 is above-deck, 1 is below-deck.

        Variables:
            - Utilization: Current state of onboard cargo (bay,deck,cargo_class,transport)
            - POD_locations: Indicator to show PODs loaded in locations (bay,deck,P)
            - Min_pod: Minimum POD location based on POD_locations (bay,deck)

        Utilization is filled/emptied incrementally. Hence, we have certain circumstances to observe utilization:
            - Step after reset: Utilization is empty
            - Step of new POL:  Discharge utilization destined for new POL
            - Any other step:   Load utilization of current cargo_class and transport

        Two ways to prevent hatch overstowage:
        - If above-deck is empty, we can freely place below-deck. Otherwise, we need to restow above-deck directly.
            E.g.:
                    | 3 | 3 | o |
                    +---+---+---+
                    | x | x | o |   , where int is min_pod of location, x is blocked location, o is open location

        - Above-deck actions are allowed if current POD <= min_pod below-deck. Otherwise, we need to restow
            above-deck when below-deck will be discharged.
            E.g.:   POD = 2
                    | x | o | o |
                    +---+---+---+
                    | 1 | 2 | 3 |   , where int is min_pod of location, x is blocked location, o is open location
        """
        # Create mask:
        mask = mask.view(-1, self.B, self.D)
        # Action below-deck (d=1) allowed if above-deck (d=0) is empty
        mask[:, :, 1] = pod_locations[:, :, 0, :].sum(dim=-1) == 0
        # Action above-deck (d=0) allowed if POD <= min_pod below deck (d=1)
        mask[:, :, 0] = pod.unsqueeze(-1) <= min_pod[:, :, 1]
        return mask.view(-1, self.B*self.D)

    # Update state
    def _update_state_discharge(self, utilization:Tensor, disc_idx:Tensor,) -> Tensor:
        """Update state as result of discharge"""
        utilization[:, :, :, disc_idx, :] = 0.0
        return utilization

    def _update_state_loading(self, action: Tensor, utilization: Tensor,
                              tau:Tensor, k:Tensor,) -> Tensor:
        """Transition to the next state based on the action."""
        new_utilization = utilization.view(-1, self.B, self.D, self.T, self.K).clone()
        new_utilization[:, :, :, tau, k] = action
        return new_utilization

    def _update_next_state(self, utilization: Tensor, target_long_crane:Tensor, long_crane_moves:Tensor,
                           realized_demand:Tensor, demand_obs:Dict, t:Tensor,) \
            -> Dict[str, Tensor]:
        """Update next state, following options:
        - Next step moves to new port POL+1
        - Next step moves to new transport (POL, POD-1)
        - Last step of episode; compute excess crane moves at last port
        """
        # Get cargo parameters
        pol, pod, tau, k, rev = self._extract_cargo_parameters_for_step(t[0])

        # Check next port with t - 1
        load_idx, disc_idx, moves_idx = self._precompute_for_step(pol)
        # Next port with discharging; Update utilization, observed demand and target long crane
        if self.next_port_mask[t-1].any():
            utilization = self._update_state_discharge(utilization, disc_idx)
            target_long_crane = self._compute_target_long_crane(realized_demand, moves_idx)
            long_crane_moves = self._compute_long_crane(utilization, pol)
            if self.demand_uncertainty:
                demand_obs["observed_demand"][:, load_idx, :] = realized_demand[:, load_idx, :]

        # Update observed and expected demand by setting to 0
        demand_obs["observed_demand"][:, tau, k] = 0
        demand_obs["expected_demand"][:, tau, k] = 0
        demand_obs["std_demand"][:, tau, k] = 0

        # Update residual lc capacity: target - actual load and discharge moves
        residual_lc_capacity = target_long_crane.unsqueeze(-1) - long_crane_moves

        # Get output
        return {
            "current_demand": realized_demand[:, tau, k],
            "observed_demand": demand_obs["observed_demand"],
            "expected_demand": demand_obs["expected_demand"],
            "std_demand":demand_obs["std_demand"],
            "utilization": utilization,
            "location_utilization": (utilization * self.teus.view(1,1,1,1,-1)).sum(dim=(-2,-1)),
            "location_weight": (utilization * self.weights.view(1,1,1,1,-1)).sum(dim=(-2,-1)),
            "target_long_crane": target_long_crane,
            "residual_lc_capacity": residual_lc_capacity,
        }

    # Compact formulation
    def _compact_form_shapes(self, ):
        """Define shapes for compact form"""
        self.n_demand = 1
        self.n_stability = 4
        # self.n_cranes = self.B - 1
        self.n_action = self.B * self.D
        self.n_constraints = self.n_demand + self.n_stability #+ self.n_cranes

    def _create_constraint_matrix(self, shape: Tuple[int, int, int, int], ):
        """Create constraint matrix A for compact constraints Au <= b"""
        # [1, LM-TW, TW-LM, VM-TW, TW-VM]
        A = th.ones(shape, device=self.generator.device, dtype=self.float_type)
        A *= self.constraint_signs.view(-1, 1, 1, 1)
        A[self.n_demand:self.n_demand + self.n_stability] *= self.stability_params_lhs.view(self.n_stability, self.B*self.D, 1, self.K,)
        return A.view(self.n_constraints, self.B*self.D, -1)

    def create_lhs_A(self, lhs_A:Tensor, t:Tensor) -> Tensor:
        """Get A_t based on ordered timestep"""
        order_t = self.ordered_steps[t[0]]
        lhs_A[:] = self.A[:,:, order_t].clone()
        return lhs_A

    def create_rhs(self, utilization:Tensor, current_demand:Tensor, batch_size) -> Tensor:
        """Create b_t based on current utilization and demand"""
        # Get rhs = [current_demand, LM_ub, LM_lb, VM_ub, VM_lb]
        # Stability constraints
        A = self.swap_signs_stability.view(-1, 1, 1,) * self.A.clone()
        # Note util is filled on k,tau derived from order_t, i.e., util and A are static!
        rhs = utilization.view(*batch_size, -1) @ A.view(self.n_constraints, -1).T
        # Demand constraint
        rhs[:, :self.n_demand] = current_demand.view(-1, 1)
        return rhs

    # Precomputes
    def _precompute_order_max_distance_then_priority(self):
        """Get ordered steps with transports in descending order of distance
        Suppose (k,tau) = (k, (POL,POD), then we have the following ordered set:
        { (0, (0,P-1)), (1, (0,P-1)), ..., (K-1, (0,P-1));
          (0, (0,P-2)), (1, (0,P-2)), ..., (K-1, (0,P-2));
          ...
          (0, (1,P-1)), (1, (1,P-1)), ..., (K-1, (1,P-1));
          (0, (1,P-2)), (1, (1,P-2)), ..., (K-1, (1,P-2));
          ...
          (0, (P-2,P-1)), (1, (P-2,P-1)), ..., (K-1, (P-2,P-1)) }
        """
        # Initialize steps and idx
        steps = th.zeros(self.T*self.K, dtype=th.int64, device=self.generator.device)
        idx = 0
        # We use loops for readability and simplicity, only because it is part of initialization
        for pol in range(self.P - 1):
            for pod in range(self.P - 1, pol, -1):
                # Get the transport index of (POL,POD)
                tau = get_transport_from_pol_pod(pol, pod, self.transport_idx)
                # Create a range of k values for this combination and store the result
                steps[idx:idx + self.K] = th.arange(self.K, device=self.generator.device, dtype=self.float_type) + tau * self.K
                idx += self.K
        return steps

    def _precompute_order_greedy_revenue(self):
        """Get ordered steps with transports in descending order of revenue per capacity usage:
        - Revenue per capacity: revenue / (teus * weights * duration)"""
        # Init
        steps = th.zeros(self.T*self.K, dtype=th.int64, device=self.generator.device)
        cap_usage = torch.einsum("j,i->ij", self.duration, (self.teus*self.weights))
        self.revenue_per_capacity = self.revenues_matrix / cap_usage
        idx = 0
        for pol in range(self.P - 1):
            # Create a mask for `revenue_per_capacity` where `loads` is True
            loads = self.load_transport[pol].expand(self.K, -1)
            masked_revenues = torch.where(loads, self.revenue_per_capacity, float("-inf"))  # Use -inf to exclude non-loads

            # Get argsort indices of the max values in descending order
            sorted_indices = torch.argsort(masked_revenues.T.flatten(), descending=True)
            # Filter out indices corresponding to -inf
            valid_indices = sorted_indices[masked_revenues.T.flatten()[sorted_indices] > float("-inf")]
            # Store the valid indices in the steps array
            steps[idx:idx + len(valid_indices)] = valid_indices
            idx += len(valid_indices)
        return steps

    def _precompute_order_standard(self):
        """Get standard order of steps;
        - POL, POD are in ascending order
        - K is in ascending order but based on priority"""
        return th.arange(self.T*self.K, device=self.generator.device, dtype=th.int64)


    def _add_padding(self, *inputs) -> List[Tensor]:
        """For any number of inputs, add a zero padding at the end of vector"""
        output = []
        for input_tensor in inputs:
            padded_tensor = th.cat([input_tensor, self.padding])
            output.append(padded_tensor)
        return output

    def _precompute_for_step(self, pol:Tensor) -> Tuple[Tensor,Tensor,Tensor]:
        """Precompute variables and index masks for the current step"""
        # Index masks
        load_idx = self.load_transport[pol]
        disc_idx = self.discharge_transport[pol]
        moves_idx = self.moves_idx[pol]
        return load_idx, disc_idx, moves_idx

    def _precompute_revenues(self, reduce_long_revenue=0.3) -> Tensor:
        """Precompute matrix of revenues with shape [K, T]"""
        # Initialize revenues and pod_grid
        revenues = th.zeros((self.K, self.P, self.P), device=self.generator.device, dtype=self.float_type) # Shape: [K, P, P]
        pol_grid, pod_grid = th.meshgrid(self.ports, self.ports, indexing='ij')  # Shapes: [P, P]
        duration_grid = (pod_grid-pol_grid).to(revenues.dtype) # Shape: [P, P]
        # Compute revenues
        mask = th.arange(self.K, device=self.generator.device, dtype=self.float_type) < self.K // 2 # Spot/long-term mask
        revenues[~mask] = duration_grid # Spot market contracts
        revenues[mask] = (duration_grid * (1 - reduce_long_revenue)) # Long-term contracts
        i, j = th.triu_indices(self.P, self.P, offset=1) # Get above-diagonal indices of revenues
        # Add 0.1 for variable revenue per container, regardless of (k,tau)
        return revenues[:, i, j] + 0.1 # Shape: [K, T], where T = P*(P-1)/2

    def _precompute_transport_sets(self):
        """Precompute transport sets based on POL with shape(s): [P, T]"""
        # Note: transport sets in the environment do not depend on batches for efficiency.
        # Hence, implementation only works for batches with the same episodic step (e.g., single-step MDP)

        # Get transport sets for demand
        p = th.arange(self.P, device=self.generator.device, dtype=self.float_type).view(-1,1)
        self.load_transport = get_load_transport(self.transport_idx, p)
        self.previous_load_transport = get_load_transport(self.transport_idx, p-1)
        self.discharge_transport = get_discharge_transport(self.transport_idx, p)
        self.not_on_board_transport = get_not_on_board_transport(self.transport_idx, p)
        self.remain_on_board_transport = get_remain_on_board_transport(self.transport_idx, p)
        self.moves_idx = self.load_transport + self.discharge_transport

    def _precompute_transport_sets_episode(self):
        """Precompute transport sets based on POL with shape(s): [Seq, T]"""
        # Get transport sets for demand
        pol_t = self.pol[:-1].view(-1,1)
        self.load_transport_episode = get_load_transport(self.transport_idx, pol_t)
        self.previous_load_transport_episode = get_load_transport(self.transport_idx, pol_t-1)
        self.discharge_transport_episode = get_discharge_transport(self.transport_idx, pol_t)
        self.not_on_board_transport_episode = get_not_on_board_transport(self.transport_idx, pol_t)
        self.remain_on_board_transport_episode = get_remain_on_board_transport(self.transport_idx, pol_t)
        self.moves_idx_episode = self.load_transport_episode + self.discharge_transport_episode

    def _precompute_next_port_mask(self):
        """Precompute next port based on POL with shape: [P, T]
        - Next port happens when POD = POL+1
        """
        # Initialize next_port
        next_port = th.zeros((self.T*self.K), dtype=th.bool, device=self.generator.device)
        pol_values = th.arange(self.P - 1, 0, -1,)  # POL values from P-1 to 1
        indices = th.cumsum(self.K * pol_values, dim=0) - 1
        next_port[indices] = True
        return next_port

    def _precompute_stability_parameters(self,):
        """Precompute lhs stability parameters for compact constraints. Get rhs by negating lhs."""
        lp_weight = self.lp_weight.unsqueeze(2).expand(-1,-1,self.D,-1)
        vp_weight = self.vp_weight.unsqueeze(1).expand(-1,self.B,-1,-1)
        p_weight = th.cat([lp_weight, lp_weight, vp_weight, vp_weight], dim=0)
        target = torch.tensor([self.LCG_target, self.LCG_target, self.VCG_target, self.VCG_target],
                              device=self.generator.device, dtype=self.float_type).view(-1,1,1,1)
        delta = torch.tensor([self.stab_delta, -self.stab_delta, self.stab_delta, -self.stab_delta],
                             device=self.generator.device, dtype=self.float_type).view(-1,1,1,1)
        output = p_weight - self.weights.view(1,1,1,self.K) * (target + delta)
        return output.view(-1, self.B*self.D, self.K,)